grpcserver:
    host: 0.0.0.0
    port: "9001"
mysql:
    dsn: ""
    conn_max_lifetime: 5m0s
    max_open_conns: 10
    max_idle_conns: 10
auth:
    access-secret-key: "qwerty"
    access-key-prefix: access-key
    access-key-ttl: 15m0s
    refresh-secret-key: "qwerty"
    refresh-key-prefix: refresh-key
    refresh-key-ttl: 120h0m0s